### PR TITLE
V2.0.0

### PR DESCRIPTION
**Pull request by zonotope**
Resolve master conflicts, bump dependency versions, and use doo + cljs.test to run tests.

### CODE REVIEW

**Comment by borkdude** [comment]
@zonotope I'm interested in this upgrade to cljs.test, etc. since it makes contributing to this project friendlier. Can you review your PR to see if it's still up to date? Is the work on the 2.0.0 branch complete for merge?

**Comment by zonotope** [comment]
@borkdude last I checked this branch was ready for merge from my end. It just hasn't been merged by the maintainers. I'm ok with merging, but I don't have that power.

**Comment by borkdude** [comment]
@zonotope Why is this branch called V2.0.0? Can you turn the version number to 1.2.4-SNAPSHOT?

**Comment by borkdude** [comment]
@zonotope If you're interested in joining secretary as a maintainer, please join the #clj-commons channel on Slack for a quick conversation.

**Comment by noprompt** [comment]
@borkdude This was called V2.0.0 because it was supposed to be the next iteration of the library. This branch was supposed to have been merged into master eventually. The diff you're looking at is the diff between the two V2.0.0 branches and not the diff with master so making the version number `1.2.4-SNAPSHOT` would be incorrect.

IIRC the remaining work on this branch is to update the README to reflect the changes but I can't remember all of them in detail.

**Comment by zonotope** [comment]
@borkdude if I remember correctly, I opened this pr against master previously to make some minor improvements. There had already been some heavy development on a v2.0 branch previously, but it needed a little more work to get over the finish line. I merged that branch into this one and made those improvements, but it hasn't been merged back into master yet. There is some more discussion about this at this pr: https://github.com/clj-commons/secretary/pull/50

I don't think I have enough free-cycles at this time to join as a maintainer, but I am interested in helping get this out where I can.

**Comment by noprompt** [comment]
@borkdude I think [the solution](https://github.com/clj-commons/secretary/pull/50#issuecomment-172418822) @zonotope had of cutting a 2.0.0 with an identifier is probably the best way to start pushing 2.0.0 forward.

**Pull request merged**
